// AUTO-GENERATED by scripts/sync-verifier.js
export const AUTO_CONTRACT_ADDRESS = "0x401975c145967cAa32d4B63Bf8A60Cd721b64F4F";
export const AUTO_CHAIN_ID = 1337;
export const AUTO_CERT_ID = "0x306f339c2ff94d6d36daaf6a0d98b8996dc7143bee6685af03c69c931f572d17";
export const AUTO_CID = "bafybeignk3h4m5kca7r7skgg53mtq2g2quyhlhbptewx2ivkbjggjb25iu";
export const AUTO_CONTENT_HASH = "0x287f131639a15f68be26505c6b1d682e7604db674e209fb708ac2dc14e631af0";
